# Site settings
title: Devin Zhang
description: 'Personal Web Page'
baseurl: ''
profilepic: 'assets/images/dwz.jpg'
bkimage: 'assets/images/bk.jpg'
font_awesome: 'd68e3e64c8.js'

author:
  name: 'Devin Zhang'
  email: devinz5050@gmail.com
  github_username:  Zdevin555
  linkedin_username:  dz5

sass:
    sass_dir: _sass
    style: compressed

